### ISSUE TITLE
NeuroMarketing dataset

### ISSUE THREAD

**Issue by Timopheym** [meagmohit/EEG-Datasets#1]
Sorry @meagmohit,  can you tell where did you get NeuroMarketing dataset? I can't load and analyse it without knowing Sampling rate and channels names.
Thanks a lot for a nice list!

**Comment by meagmohit** [comment]
Hi,

The article on this dataset is below,
*Analysis of EEG signals and its application to neuromarketing*

I've updated the GitHub repo too. Thanks, and feel free to contribute to
update the list.

Mohit

**Comment by 1ihsan** [comment]
Sorry @meagmohit, can you tell where did you get NeuroMarketing dataset?  I can't load and analyse. Please help me.
Thanks a lot for a nice list!
