### ISSUE TITLE
hi,my friend,thank you for supply the info about EEG dataset，i have a question to ask you

### ISSUE THREAD

**Issue by varyshare** [meagmohit/EEG-Datasets#2]
hi,my friend,thank you for supply the info about EEG dataset，i have a question to ask you

I want do a research about emotion, but I cannot download the DEAP dataset. Do you have a DEAP data?
If you have, wish you could send me one, thank you. my email: [cs-taoli@qq.com](mailto:cs-taoli@qq.com)

tao li
from China

**Comment by meagmohit** [comment]
Hi,

Please follow the instructions from this link to download this dataset.
http://www.eecs.qmul.ac.uk/mmv/datasets/deap/download.html

I do not have a copy of the dataset, but, if you follow the guidelines as
mentioned in the above email you'll be able to download the dataset.

Thanks,
Mohit
