### ISSUE TITLE
Small typo spotted

### ISSUE THREAD

**Issue by alik604** [meagmohit/EEG-Datasets#6]
Small typo spotted

> Confusion during MOOC: 10 students watching MOOC videos in two categories - **confusing (e.g., basic maths)** and **non-confusing (e.g., quantum theory).** 2-minute duration 10 videos in each category. Recorded from single-channel wireless MindSet over frontal channel. [Article]

_please close this issue when you see this_

**Comment by meagmohit** [comment]
Hi,

I do not understand what is the typo here?

**Comment by alik604** [comment]
'confusing' is a for synonym for 'complex'. So it should be
> confusing (e.g., quantum theory) and non-confusing (e.g., basic maths)
