### ISSUE TITLE
Confusion during MOOC

### ISSUE THREAD

**Issue by haydn-jones** [meagmohit/EEG-Datasets#9]
The examples are backwards for confusing and non-confusing in the **Confusion during MOOC** dataset. Basic maths should be non-confusing and quantum theory should be confusing: 

Confusion during MOOC: 10 students watching MOOC videos in two categories - **confusing (e.g., basic maths)** and **non-confusing (e.g., quantum theory)**. 2-minute duration 10 videos in each category. Recorded from single-channel wireless MindSet over frontal channel. [Article]

**Comment by meagmohit** [comment]
Thanks for letting me know. I fixed it.
